import { GuestType, TimePeriod } from "../types";

export const menuByTimeAndGuest: Record<TimePeriod, Record<GuestType, string[]>> = {
  "Pagi": {
    "PERTA": [
      "Nasi Uduk",
      "Nasi Kuning",
      "Bubur Ayam",
      "Lontong Sayur",
      "Roti Bakar",
      "Donat",
      "Kopi Hitam",
      "Teh Manis",
      "Teh Tawar",
      "Air Mineral",
    ],
    "Regular": [
      "Nasi Uduk",
      "Nasi Kuning",
      "Bubur Ayam",
      "Lontong Sayur",
      "Roti Bakar",
      "Donat",
      "Kopi Hitam",
      "Teh Manis",
      "Teh Tawar",
      "Air Mineral",
    ],
    "Standar": [
      "Nasi Uduk",
      "Nasi Kuning",
      "Bubur Ayam",
      "Lontong Sayur",
      "Roti Bakar",
      "Donat",
      "Kopi Hitam",
      "Teh Manis",
      "Teh Tawar",
      "Air Mineral",
    ],
    "VIP": [
      "Nasi Uduk Premium",
      "Nasi Kuning Spesial",
      "Bubur Ayam Kampung",
      "Lontong Sayur Komplit",
      "Roti Bakar Keju",
      "Sandwich Club",
      "Croissant Butter",
      "Danish Pastry",
      "Kopi Susu Premium",
      "Susu Segar",
      "Jus Jeruk Fresh",
      "Yogurt Buah",
    ],
    "VVIP": [
      "Nasi Liwet Komplit Premium",
      "Bubur Ayam Abalone",
      "Eggs Benedict",
      "Smoked Salmon Bagel",
      "Croissant Almond Premium",
      "French Toast",
      "Pancake Blueberry",
      "Waffle Belgium",
      "Cappuccino Premium",
      "Latte Macchiato",
      "Fresh Orange Juice",
      "Smoothie Bowl",
      "Champagne Breakfast",
    ],
  },
  "Siang": {
    "PERTA": [
      "Nasi Box Ayam Goreng",
      "Nasi Box Ayam Bakar",
      "Nasi Goreng",
      "Mie Goreng",
      "Nasi Putih + Lauk",
      "Sayur Asem",
      "Capcay",
      "Air Mineral",
      "Teh Botol",
      "Es Teh",
    ],
    "Regular": [
      "Nasi Box Ayam Goreng",
      "Nasi Box Ayam Bakar",
      "Nasi Goreng",
      "Mie Goreng",
      "Nasi Putih + Lauk",
      "Sayur Asem",
      "Capcay",
      "Air Mineral",
      "Teh Botol",
      "Es Teh",
    ],
    "Standar": [
      "Nasi Box Ayam Goreng",
      "Nasi Box Ayam Bakar",
      "Nasi Goreng",
      "Mie Goreng",
      "Nasi Putih + Lauk",
      "Sayur Asem",
      "Capcay",
      "Air Mineral",
      "Teh Botol",
      "Es Teh",
    ],
    "VIP": [
      "Nasi Box Ayam Goreng Bumbu Rujak",
      "Nasi Box Rendang Sapi",
      "Nasi Box Ikan Bakar",
      "Nasi Goreng Seafood",
      "Mie Goreng Spesial",
      "Sop Iga Sapi",
      "Ayam Geprek Sambal Matah",
      "Jus Buah Segar",
      "Es Kelapa Muda",
      "Soft Drink",
    ],
    "VVIP": [
      "Nasi Box Wagyu Teriyaki",
      "Nasi Box Salmon Teriyaki",
      "Nasi Box Tenderloin Steak",
      "Nasi Goreng Lobster",
      "Spaghetti Aglio Olio Premium",
      "Grilled Chicken Premium",
      "Seafood Pasta",
      "Caesar Salad",
      "Mineral Water Premium",
      "Fresh Fruit Juice",
      "Iced Lemon Tea",
      "Dessert (Tiramisu/Panna Cotta)",
    ],
  },
  "Sore": {
    "PERTA": [
      "Kue Lapis",
      "Risoles",
      "Lemper",
      "Pastel",
      "Pisang Goreng",
      "Tahu Isi",
      "Kopi",
      "Teh",
      "Air Mineral",
    ],
    "Regular": [
      "Kue Lapis",
      "Risoles",
      "Lemper",
      "Pastel",
      "Pisang Goreng",
      "Tahu Isi",
      "Kopi",
      "Teh",
      "Air Mineral",
    ],
    "Standar": [
      "Kue Lapis",
      "Risoles",
      "Lemper",
      "Pastel",
      "Pisang Goreng",
      "Tahu Isi",
      "Kopi",
      "Teh",
      "Air Mineral",
    ],
    "VIP": [
      "Kue Lapis Legit",
      "Risoles Mayo",
      "Lemper Ayam Premium",
      "Pastel Tutup",
      "Kue Cubit Premium",
      "Martabak Mini Coklat Keju",
      "Bika Ambon",
      "Kopi Latte",
      "Thai Tea",
      "Jus Buah",
    ],
    "VVIP": [
      "Petit Fours Assorted",
      "French Macaron",
      "Chocolate Eclair",
      "Red Velvet Cake",
      "Tiramisu Cup",
      "Cheese Cake",
      "Fruit Tart",
      "Espresso Premium",
      "Cappuccino",
      "Smoothie",
      "Sparkling Water",
    ],
  },
  "Malam": {
    "PERTA": [
      "Nasi Box Ayam",
      "Nasi Liwet",
      "Soto Ayam",
      "Gado-Gado",
      "Pecel",
      "Bakso",
      "Air Mineral",
      "Teh Panas",
      "Kopi",
    ],
    "Regular": [
      "Nasi Box Ayam",
      "Nasi Liwet",
      "Soto Ayam",
      "Gado-Gado",
      "Pecel",
      "Bakso",
      "Air Mineral",
      "Teh Panas",
      "Kopi",
    ],
    "Standar": [
      "Nasi Box Ayam",
      "Nasi Liwet",
      "Soto Ayam",
      "Gado-Gado",
      "Pecel",
      "Bakso",
      "Air Mineral",
      "Teh Panas",
      "Kopi",
    ],
    "VIP": [
      "Nasi Box Premium Ayam Bakar",
      "Nasi Timbel Komplit",
      "Soto Betawi",
      "Rawon Daging",
      "Nasi Bakar Ayam Sisit",
      "Mie Ayam Spesial",
      "Bakso Urat Premium",
      "Soft Drink",
      "Jus Alpukat",
      "Es Kelapa Muda",
    ],
    "VVIP": [
      "Nasi Box Wagyu Premium",
      "Nasi Timbel Iga Bakar Premium",
      "Beef Wellington",
      "Grilled Salmon Premium",
      "Lamb Chop",
      "Seafood Platter",
      "Sushi & Sashimi Set",
      "Premium Dessert",
      "Wine Selection",
      "Mineral Water Premium",
      "Fresh Juice Bar",
    ],
  },
};

export const tamuMultiplier: Record<GuestType, number> = {
  "PERTA": 1,
  "Regular": 1,
  "Standar": 1,
  "VIP": 1.5,
  "VVIP": 2,
};
